version: '3'
services:
  db:
    image: postgres
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5432'

  web:
    build: .
    command: bash -c "foreman start"
    volumes:
      - .:/app
    environment:
      BUNDLE_PATH: /app/vendor/bundle
      REDIS_URL: redis://redis:6379
    ports:
      - '3000:3000'
    depends_on:
      - db
      - redis
    stdin_open: true
    tty: true

  redis:
    image: redis:6.0
    ports:
     - 6379:6379

volumes:
  postgresql_data:
